# Generated by Django 5.2.8 on 2025-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
