# Generated by Django 5.2.8 on 2025-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_plan_stripe_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_pid',
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
