# Generated by Django 5.2.8 on 2025-12-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestrun',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='backtestrun',
            name='start_date',
        ),
    ]
