# Generated by Django 5.2.8 on 2026-05-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0002_remove_backtestrun_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='notes',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
