# Generated by Django 5.2.8 on 2026-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_backtestrun_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
